### ISSUE TITLE
Idea for a simpler way

### ISSUE THREAD

**Issue by malhal** [PyMySQL/myloginpath#2]
Just parse the output from `my_print_defaults`

```
me@ubuntu:~$ my_print_defaults --show client
--user=me
--password=password
--host=localhost
```

**Comment by malhal** [comment]
Seems they supply a library to do this: https://github.com/mysql/mysql-utilities/blob/master/mysql/utilities/common/my_print_defaults.py

**Comment by methane** [comment]
Thanks but I don't like the idea.
