### ISSUE TITLE
ERROR if --login-path contains definition for socket

### ISSUE THREAD

**Issue by MDMSever** [PyMySQL/myloginpath#4]
pymysql.connect does not know what 'socket' is and it instead expects to get 'unix_socket'...

# Run command at the bash prompt:
# mysql_config_editor set --login-path=testProfile1 --socket=/tmp/mysql.sock --host=localhost --user=me --password
# Python code snippet
import myloginpath
import pymysql
conf = myloginpath.parse('testProfile1')
conf['unix_socket'] = conf.pop('socket')
con = pymysql.connect(**conf, db = sql_database)
#
# IF the line conf['unix_socket'] = conf.pop('socket') is left out, get the error:
# TypeError: __init__() got an unexpected keyword argument 'socket'
#

**Comment by methane** [comment]
Thank you for reporting. But this library is not only for PyMySQL/mysqlclient-python.
I don't change the option name. You need to convert it by yourself.

**Comment by MDMSever** [comment]
OK.  It’s fine.  But possibly think about adding to the documentation.  Will myloginpath load all parameters it finds from using mysql_config_editor into a **var?
