### ISSUE TITLE
mysql_config_editor emits config file with quotes

### ISSUE THREAD

**Issue by nickodell** [PyMySQL/myloginpath#6]
I've recently been running into an issue where mysql_config_editor will emit a configuration file which includes quotes. myloginpath interprets the quotes as part of the value.

This issues is caused by using MySQL 8.0.24, which came out on 2021-4-20. Here's the relevant part of the changelog:

>To enable use of spaces and other special characters within configuration values, mysql_config_editor now surrounds values it writes to the configuration file with double quote characters, and also escapes double quote characters used within values. (Bug #19953349, Bug #74691)

https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-24.html

Here's an example session:

```
$ mysql_config_editor --version
mysql_config_editor  Ver 8.0.25-0ubuntu0.20.10.1 for Linux on x86_64 ((Ubuntu))
$ mysql_config_editor set --login-path=test --host=foo
$ mysql_config_editor print --login-path=test
[test]
host = "foo"
$ python3                 
Python 3.8.6 (default, Jan 27 2021, 15:42:20) 
[GCC 10.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import myloginpath
>>> myloginpath.parse('test')
{'host': '"foo"'}
```

**Comment by nickodell** [comment]
Here's the commit where they changed it: https://github.com/mysql/mysql-server/commit/7d8028ac99730d4ccbe42d6edc11cc4f6d0cddca

**Comment by onlime** [comment]
Hi @methane! Can you please release a new version of myloginpath so that we can deploy this fix easily? I am also struggling with this since MySQL 8.0.24/8.0.25 upgrade. Thanks.

**Comment by onlime** [comment]
I am still using this workaround in `requirements.txt` to get latest `master`:

```diff
-myloginpath==0.0.2
+git+https://github.com/PyMySQL/myloginpath@master#egg=myloginpath
```

@methane may I kindly ask you again to release a new version with this fix?

**Comment by methane** [comment]
Sorry for delay. I uploaded the v0.0.3.
